In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3

In [ ]:
# Series
import pandas as Sanjana
Kavya=Sanjana.Series([1,2,3,4])
Kavya

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#list to series
import pandas as pd
marks=pd.Series([85,90,75,95])
print(marks)

0    85
1    90
2    75
3    95
dtype: int64

Pandas automatically generate index

In [ ]:
import pandas as pd
Num=[5,10,15,20,25,30,35]
data=pd.Series(Num)
Num

[5, 10, 15, 20, 25, 30, 35]

In [ ]:
#tuple to series
import pandas as pd
Num=(5,10,15,20,25,30,35)
data=pd.Series(Num)
data

0     5
1    10
2    15
3    20
4    25
5    30
6    35
dtype: int64

In [ ]:
#dict to series
import pandas as pd
dict1={'name':'jhon',
       'age':25,
       'place':'bengaluru'}
data=pd.Series(dict1)
data

name          jhon
age             25
place    bengaluru
dtype: object

In [ ]:
#numpy to array
import numpy as np
arr=np.array([10,20,30,40])
s=pd.Series(arr)
s

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#list to series
import pandas as pd
marks=pd.Series([85,90,75,95,80])
print(marks)

0    85
1    90
2    75
3    95
4    80
dtype: int64

In [ ]:
#print the values greater than 85
import pandas as pd
marks=pd.Series([85,90,75,95,80])
print(marks[marks>=85])

0    85
1    90
3    95
dtype: int64

In [ ]:
import pandas as pd
demo=pd.Series([10,20,30,40,50])
print(demo)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#dict to pandas
import pandas as pd
Student={'name':'sanjana',
         'age':20,
         'place':'gadag',
         'collge':'JT collge',
         'year':2025,
         'Result':'pass'
       }
Student
demo=pd.Series(Student)
demo
print(demo['place'])
print(demo['Result'])
print(demo['name'])
print(demo['collge'])
print(demo['year'])
print(demo[-2])

gadag
pass
sanjana
JT collge
2025
2025

/tmp/ipykernel_875/86081706.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[-2])

In [ ]:
import pandas as pd
arr=[86,45,89,34,67,88,94,12]
data=pd.Series(arr)
print(data[data >82])
print([data>82])
data

0    86
2    89
5    88
6    94
dtype: int64
[0     True
1    False
2     True
3    False
4    False
5     True
6     True
7    False
dtype: bool]

0    86
1    45
2    89
3    34
4    67
5    88
6    94
7    12
dtype: int64

In [ ]:
#multiply
import pandas as pd
marks=pd.Series([10,20,30,40,50])
print(marks*2)

0     20
1     40
2     60
3     80
4    100
dtype: int64

In [ ]:
#.dtype
marks.dtype

dtype('int64')

In [ ]:
#.size
marks.size

5

In [ ]:
# .shape
marks.shape

(5,)

In [ ]:
# .index
marks.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# .values
marks.values

array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np
import pandas as pd
arr=np.array([80,90,95])
arr+=5
arr
new=pd.Series(arr)
new
print(new*2)
print(new[new>80])

0    170
1    190
2    200
dtype: int64
0     85
1     95
2    100
dtype: int64

data frame-more than one column

In [ ]:
#DataFrame progress
#1.Dict to dataframe
import pandas as pd
pd.DataFrame({'Name':['Rahul'],'Age':[22]})

    Name  Age
0  Rahul   22

In [ ]:
import pandas as pd
demo={'reg no':[11,12,13,14,15,16],
      'name':['shashi','sanju','poorna','bindu','keerti','spoorti'],
      'age':[12,15,13,14,18,19],
      'place':['mumbai','delhi','kolkata','karnataka','kerala','tamilnadu']
      }
demo

data=pd.DataFrame(demo)
data

   reg no     name  age      place
0      11   shashi   12     mumbai
1      12    sanju   15      delhi
2      13   poorna   13    kolkata
3      14    bindu   14  karnataka
4      15   keerti   18     kerala
5      16  spoorti   19  tamilnadu

In [ ]:
#2.csv file to dataframe
import pandas as pd


df=pd.read_csv("/content/Employee.csv")
df

   Emp id     Name  Salary company
0      10  Sanjana   80000   micro
1      20   Bhavya   70000   wipro
2      30    Isiri   60000   cisco
3      40  bhavani   56000  google

In [ ]:
#print the name of the csv file
df['Name']

0    Sanjana
1     Bhavya
2      Isiri
3    bhavani
Name: Name, dtype: object

In [ ]:
(df['Name'])

0    Sanjana
1     Bhavya
2      Isiri
3    bhavani
Name: Name, dtype: object

In [ ]:
df['Salary']

0    80000
1    70000
2    60000
3    56000
Name: Salary, dtype: int64

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Emp.xlsx")
data

      Name   Id Dept  Salary
0  Sanjana  101   IT   25000
1    Kavya  102   IT   30000
2     tomy  103   HR   35000
3     Motu  104   IT   40000

In [ ]:
import pandas as pd
data=pd.read_csv('Employee.csv')
data

   Emp id     Name  Salary company
0      10  Sanjana   80000   micro
1      20   Bhavya   70000   wipro
2      30    Isiri   60000   cisco
3      40  bhavani   56000  google

In [ ]:
data['Emp id']

0    10
1    20
2    30
3    40
Name: Emp id, dtype: int64

In [ ]:
data['Salary']

0    80000
1    70000
2    60000
3    56000
Name: Salary, dtype: int64

In [ ]:
print(df[['Name','Emp id']])

      Name  Emp id
0  Sanjana      10
1   Bhavya      20
2    Isiri      30
3  bhavani      40

In [ ]:
data["Age"]=[16,26,36,49]
data.to_csv('Age',index=False)
data

   Emp id     Name  Salary company  Age
0      10  Sanjana   80000   micro   16
1      20   Bhavya   70000   wipro   26
2      30    Isiri   60000   cisco   36
3      40  bhavani   56000  google   49

In [ ]:
data["City"]=["Bengaluru","mysuru","dubai","chennai"]
data.to_csv('City',index=False)
data

   Emp id     Name  Salary company  Age       City
0      10  Sanjana   80000   micro   16  Bengaluru
1      20   Bhavya   70000   wipro   26     mysuru
2      30    Isiri   60000   cisco   36      dubai
3      40  bhavani   56000  google   49    chennai

if we are not asign the false to index it automatically printd true

In [ ]:
data=data.drop('Age',axis=1)
data

   Emp id     Name  Salary company       City
0      10  Sanjana   80000   micro  Bengaluru
1      20   Bhavya   70000   wipro     mysuru
2      30    Isiri   60000   cisco      dubai
3      40  bhavani   56000  google    chennai

In [ ]:
data=data.drop('City',axis=1)
data

   Emp id     Name  Salary company
0      10  Sanjana   80000   micro
1      20   Bhavya   70000   wipro
2      30    Isiri   60000   cisco
3      40  bhavani   56000  google

In [ ]:
data.columns

Index(['Emp id', 'Name', 'Salary', 'company'], dtype='object')

In [ ]:
data.shape

(4, 4)

In [ ]:
data.dtypes

Emp id      int64
Name       object
Salary      int64
company    object
dtype: object

In [ ]:
data.head()

   Emp id     Name  Salary company
0      10  Sanjana   80000   micro
1      20   Bhavya   70000   wipro
2      30    Isiri   60000   cisco
3      40  bhavani   56000  google

In [ ]:
#tail()-print the last 5 rows of the dataset
data.tail()

   Emp id     Name  Salary company
0      10  Sanjana   80000   micro
1      20   Bhavya   70000   wipro
2      30    Isiri   60000   cisco
3      40  bhavani   56000  google

In [ ]:
#describe-gives the outpt with count,mean,std,min and max of the dataset
data.describe()

          Emp id       Salary
count   4.000000      4.00000
mean   25.000000  66500.00000
std    12.909944  10754.84387
min    10.000000  56000.00000
25%    17.500000  59000.00000
50%    25.000000  65000.00000
75%    32.500000  72500.00000
max    40.000000  80000.00000

In [ ]:
#info->it gives information of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Emp id   4 non-null      int64
 1   Name     4 non-null      object
 2   Salary   4 non-null      int64
 3   company  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
#printthe dataset as a excelworksheet using pd.DataFrame
import pandas as pd
employee={
    'ID':[101,102,103,104,105,106,107,108,109,110],
    'Name':['kavya','sahil','akhil','nikhil','jhanvi','bhavya','nikhita','sakshi','bhuvi','pruthvi'],
    'Dept':['IT','HR','IT','HR','IT','HR','IT','HR','IT','HR'],
    'Salary':[10000,20000,30000,40000,50000,60000,70000,80000,90000,10000000]
}
df=pd.DataFrame(employee)
df

    ID     Name Dept    Salary
0  101    kavya   IT     10000
1  102    sahil   HR     20000
2  103    akhil   IT     30000
3  104   nikhil   HR     40000
4  105   jhanvi   IT     50000
5  106   bhavya   HR     60000
6  107  nikhita   IT     70000
7  108   sakshi   HR     80000
8  109    bhuvi   IT     90000
9  110  pruthvi   HR  10000000

In [ ]:
#mean
print(df['Salary'].mean())

1045000.0

In [ ]:
#median
print(df['Salary'].median())

55000.0

In [ ]:
#df
print([df['Dept']=='IT'])

[0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8     True
9    False
Name: Dept, dtype: bool]