In [15]:
import pandas as pd
data=pd.read_excel("/content/Employee demo.xlsx")
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha    NaN       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000        NaN 2023-05-10
3    NaN      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya    NaN  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0     NaN           IT   47000      Delhi 2023-02-01
8   E109        NaN  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [16]:
data.isnull()

   Emp id   Name    Age  Gender   Dept  Salary   City  Join date
0   False  False  False   False  False   False  False      False
1   False  False   True   False  False   False  False      False
2   False  False  False   False  False   False   True      False
3    True  False  False   False  False   False  False      False
4   False  False  False   False  False   False  False      False
5   False  False   True   False  False   False  False      False
6   False  False  False   False  False   False  False      False
7   False  False  False    True  False   False  False      False
8   False   True  False   False  False   False  False      False
9   False  False  False   False  False   False  False      False

In [17]:
data.isnull().sum()

Emp id       1
Name         1
Age          2
Gender       1
Dept         0
Salary       0
City         1
Join date    0
dtype: int64

In [18]:
data.isnull().sum().sum()

np.int64(6)

In [19]:
data['City']=data['City'].fillna('Mangaluru')
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha    NaN       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3    NaN      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya    NaN  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0     NaN           IT   47000      Delhi 2023-02-01
8   E109        NaN  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [20]:
data['Age']=data['Age'].fillna(24)
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3    NaN      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0     NaN           IT   47000      Delhi 2023-02-01
8   E109        NaN  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [21]:
data['City']=data['City'].fillna('Bengaluru')
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3    NaN      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0     NaN           IT   47000      Delhi 2023-02-01
8   E109        NaN  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [22]:
data['Emp id']=data['Emp id'].fillna('E104')
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3   E104      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0     NaN           IT   47000      Delhi 2023-02-01
8   E109        NaN  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [23]:
data['Name']=data['Name'].ffill()
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3   E104      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0     NaN           IT   47000      Delhi 2023-02-01
8   E109      Sneha  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [24]:
data['Gender']=data['Gender'].bfill()
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3   E104      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0  Female           IT   47000      Delhi 2023-02-01
8   E109      Sneha  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [25]:
data.isnull().sum()

Emp id       0
Name         0
Age          0
Gender       0
Dept         0
Salary       0
City         0
Join date    0
dtype: int64

In [26]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [27]:
data.drop_duplicates()
data

  Emp id       Name    Age  Gender         Dept  Salary       City  Join date
0   E101      Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102      Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103       John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3   E104      Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106    Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105     Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108      Sneha   23.0  Female           IT   47000      Delhi 2023-02-01
8   E109      Sneha  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110      Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [28]:
data['Name']=data['Name'].str.strip()
data

  Emp id     Name    Age  Gender         Dept  Salary       City  Join date
0   E101    Akash   25.0       M           IT   45000   Bengalur 2023-01-01
1   E102    Megha   24.0       F           HR   38000    Chennai 2022-02-15
2   E103     John   28.0    Male      Finance   55000  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female           IT   48000     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female           HR  -38000    Chennai 2022-02-15
6   E105   Darshi   26.0    Male        Sales   25000   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female           IT   47000      Delhi 2023-02-01
8   E109    Sneha  -27.0  Female      Finance   52000   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male           IT  999999    Chennai 2024-01-05

In [29]:
data['Dept']=data['Dept'].str.strip()
data

  Emp id     Name    Age  Gender     Dept  Salary       City  Join date
0   E101    Akash   25.0       M       IT   45000   Bengalur 2023-01-01
1   E102    Megha   24.0       F       HR   38000    Chennai 2022-02-15
2   E103     John   28.0    Male  Finance   55000  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female       IT   48000     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male    Sales   25000   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female       HR  -38000    Chennai 2022-02-15
6   E105   Darshi   26.0    Male    Sales   25000   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female       IT   47000      Delhi 2023-02-01
8   E109    Sneha  -27.0  Female  Finance   52000   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male       IT  999999    Chennai 2024-01-05

In [30]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [31]:
data.duplicated().sum()

np.int64(1)

In [32]:
data['City']=data['City'].str.strip()
data

  Emp id     Name    Age  Gender     Dept  Salary       City  Join date
0   E101    Akash   25.0       M       IT   45000   Bengalur 2023-01-01
1   E102    Megha   24.0       F       HR   38000    Chennai 2022-02-15
2   E103     John   28.0    Male  Finance   55000  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female       IT   48000     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male    Sales   25000   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female       HR  -38000    Chennai 2022-02-15
6   E105   Darshi   26.0    Male    Sales   25000   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female       IT   47000      Delhi 2023-02-01
8   E109    Sneha  -27.0  Female  Finance   52000   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male       IT  999999    Chennai 2024-01-05

In [33]:
data.drop('Join date',axis=1)

  Emp id     Name    Age  Gender     Dept  Salary       City
0   E101    Akash   25.0       M       IT   45000   Bengalur
1   E102    Megha   24.0       F       HR   38000    Chennai
2   E103     John   28.0    Male  Finance   55000  Mangaluru
3   E104    Kavya  240.0  Female       IT   48000     Mysuru
4   E105   Darshi   26.0    Male    Sales   25000   Bengalur
5   E106  Supriya   24.0  Female       HR  -38000    Chennai
6   E105   Darshi   26.0    Male    Sales   25000   Bengalur
7   E108    Sneha   23.0  Female       IT   47000      Delhi
8   E109    Sneha  -27.0  Female  Finance   52000   Hyderbad
9   E110    Vikas   22.0    Male       IT  999999    Chennai

In [34]:
data.dtypes

Emp id               object
Name                 object
Age                 float64
Gender               object
Dept                 object
Salary                int64
City                 object
Join date    datetime64[ns]
dtype: object

In [35]:
data['Age']=data['Age'].astype(int)
data

  Emp id     Name  Age  Gender     Dept  Salary       City  Join date
0   E101    Akash   25       M       IT   45000   Bengalur 2023-01-01
1   E102    Megha   24       F       HR   38000    Chennai 2022-02-15
2   E103     John   28    Male  Finance   55000  Mangaluru 2023-05-10
3   E104    Kavya  240  Female       IT   48000     Mysuru 2023-03-20
4   E105   Darshi   26    Male    Sales   25000   Bengalur 2021-06-10
5   E106  Supriya   24  Female       HR  -38000    Chennai 2022-02-15
6   E105   Darshi   26    Male    Sales   25000   Bengalur 2021-06-10
7   E108    Sneha   23  Female       IT   47000      Delhi 2023-02-01
8   E109    Sneha  -27  Female  Finance   52000   Hyderbad 2022-08-22
9   E110    Vikas   22    Male       IT  999999    Chennai 2024-01-05

In [36]:
import numpy as np
data.loc[data['Age']<0,'Age']=np.nan
data

  Emp id     Name    Age  Gender     Dept  Salary       City  Join date
0   E101    Akash   25.0       M       IT   45000   Bengalur 2023-01-01
1   E102    Megha   24.0       F       HR   38000    Chennai 2022-02-15
2   E103     John   28.0    Male  Finance   55000  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female       IT   48000     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male    Sales   25000   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female       HR  -38000    Chennai 2022-02-15
6   E105   Darshi   26.0    Male    Sales   25000   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female       IT   47000      Delhi 2023-02-01
8   E109    Sneha    NaN  Female  Finance   52000   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male       IT  999999    Chennai 2024-01-05

In [37]:
data.loc[data['Salary'] < 10000,'Salary']=np.nan
data

  Emp id     Name    Age  Gender     Dept    Salary       City  Join date
0   E101    Akash   25.0       M       IT   45000.0   Bengalur 2023-01-01
1   E102    Megha   24.0       F       HR   38000.0    Chennai 2022-02-15
2   E103     John   28.0    Male  Finance   55000.0  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female       IT   48000.0     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male    Sales   25000.0   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female       HR       NaN    Chennai 2022-02-15
6   E105   Darshi   26.0    Male    Sales   25000.0   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female       IT   47000.0      Delhi 2023-02-01
8   E109    Sneha    NaN  Female  Finance   52000.0   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male       IT  999999.0    Chennai 2024-01-05

In [38]:
data.loc[data['Salary'] > 100000,'Salary']=np.nan
data

  Emp id     Name    Age  Gender     Dept   Salary       City  Join date
0   E101    Akash   25.0       M       IT  45000.0   Bengalur 2023-01-01
1   E102    Megha   24.0       F       HR  38000.0    Chennai 2022-02-15
2   E103     John   28.0    Male  Finance  55000.0  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female       IT  48000.0     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male    Sales  25000.0   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female       HR      NaN    Chennai 2022-02-15
6   E105   Darshi   26.0    Male    Sales  25000.0   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female       IT  47000.0      Delhi 2023-02-01
8   E109    Sneha    NaN  Female  Finance  52000.0   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male       IT      NaN    Chennai 2024-01-05

In [39]:
data['Gender']=data['Gender'].replace({"M":"Male","F":"Female"})
data

  Emp id     Name    Age  Gender     Dept   Salary       City  Join date
0   E101    Akash   25.0    Male       IT  45000.0   Bengalur 2023-01-01
1   E102    Megha   24.0  Female       HR  38000.0    Chennai 2022-02-15
2   E103     John   28.0    Male  Finance  55000.0  Mangaluru 2023-05-10
3   E104    Kavya  240.0  Female       IT  48000.0     Mysuru 2023-03-20
4   E105   Darshi   26.0    Male    Sales  25000.0   Bengalur 2021-06-10
5   E106  Supriya   24.0  Female       HR      NaN    Chennai 2022-02-15
6   E105   Darshi   26.0    Male    Sales  25000.0   Bengalur 2021-06-10
7   E108    Sneha   23.0  Female       IT  47000.0      Delhi 2023-02-01
8   E109    Sneha    NaN  Female  Finance  52000.0   Hyderbad 2022-08-22
9   E110    Vikas   22.0    Male       IT      NaN    Chennai 2024-01-05

In [40]:
data['Dept'].unique()

array(['IT', 'HR', 'Finance', 'Sales'], dtype=object)

In [41]:
data['Dept'].value_counts()

Dept
IT         4
HR         2
Finance    2
Sales      2
Name: count, dtype: int64

In [42]:
data.describe()

              Age        Salary            Join date
count    9.000000      8.000000                   10
mean    48.666667  41875.000000  2022-08-23 12:00:00
min     22.000000  25000.000000  2021-06-10 00:00:00
25%     24.000000  34750.000000  2022-02-15 00:00:00
50%     25.000000  46000.000000  2022-10-27 00:00:00
75%     26.000000  49000.000000  2023-03-08 06:00:00
max    240.000000  55000.000000  2024-01-05 00:00:00
std     71.772209  11544.169833                  NaN

In [43]:
data['Salary'].var()

133267857.14285715

In [47]:
data.shape

(10, 8)