In [ ]:
import pandas as pd
data=pd.read_excel("/content/Student Data.xlsx")
data

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
#1.info()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student ID      14 non-null     object
 1   Name            14 non-null     object
 2   Age             14 non-null     float64
 3   Gender          15 non-null     object
 4   Course          14 non-null     object
 5   Marks           14 non-null     float64
 6   City            14 non-null     object
 7   Admission Date  15 non-null     object
dtypes: float64(2), object(6)
memory usage: 1.1+ KB

In [ ]:
#2.dtypes
data.dtypes

Student ID         object
Name               object
Age               float64
Gender             object
Course             object
Marks             float64
City               object
Admission Date     object
dtype: object

In [ ]:
#3.head
data.head(6)

  Student ID    Name    Age  Gender Course  Marks       City Admission Date
0       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1       S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2       S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3       S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4       S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5       S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023

In [ ]:
#4.tail()
data.tail()

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
10       S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
#4 isnull()
data.isnull()

    Student ID   Name    Age  Gender  Course  Marks   City  Admission Date
0        False  False  False   False   False  False  False           False
1        False  False   True   False   False  False  False           False
2        False  False  False   False   False  False  False           False
3        False  False  False   False   False  False  False           False
4        False  False  False   False   False  False  False           False
5        False  False  False   False   False  False  False           False
6         True  False  False   False   False  False  False           False
7        False   True  False   False   False  False  False           False
8        False  False  False   False   False  False  False           False
9        False  False  False   False   False  False  False           False
10       False  False  False   False   False  False  False           False
11       False  False  False   False    True  False  False           False
12       False  False  False   False   False   True  False           False
13       False  False  False   False   False  False   True           False
14       False  False  False   False   False  False  False           False

In [ ]:
#5 isnull().sum()
data.isnull().sum()

Student ID        1
Name              1
Age               1
Gender            0
Course            1
Marks             1
City              1
Admission Date    0
dtype: int64

In [ ]:
#6 isnull().sum().sum()
data.isnull().sum().sum()

np.int64(6)

In [ ]:
#7.duplicated()
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
dtype: bool

In [ ]:
#duplicated().sum()
data.duplicated().sum()

np.int64(1)

In [ ]:
data.drop_duplicates('Admission Date')

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['City']=data['City'].fillna("Nepal")
data

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['City']=data['City'].fillna('Nepal')
data

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
import numpy as np
data.loc[data['Age']>80,'Age']=np.nan
data

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   NaN    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi  21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Gender']=data['Gender'].replace({'F':'Female','M':'Male'})
data

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   NaN    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi  21.0    Male    MCA   95.0      Delhi     01-08-2023
7        S208     NaN  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju -19.0  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Course']=data['Course'].fillna('MCA')
data

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   NaN    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi  21.0    Male    MCA   95.0      Delhi     01-08-2023
7        S208     NaN  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju -19.0  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    MCA   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Age']=data['Age'].fillna(25)
data

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya  25.0  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  25.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi  21.0    Male    MCA   95.0      Delhi     01-08-2023
7        S208     NaN  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju -19.0  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    MCA   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Age']=data['Age'].astype(int)
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Marks']=data['Marks'].fillna(78)
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA   78.0  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Marks']=data['Marks'].fillna(69)
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA   78.0  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data['Marks']=data['Marks'].astype(int)
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    -45    Chennai     15-07-2023
6         NaN    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA     76     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA     78  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA     68      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
data.describe()
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    -45    Chennai     15-07-2023
6         NaN    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA     76     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA     78  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA     68      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
data.shape

(15, 8)

In [ ]:
data.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City',
       'Admission Date'],
      dtype='object')

In [ ]:
data.isnull().sum()

Student ID        1
Name              1
Age               0
Gender            0
Course            0
Marks             0
City              0
Admission Date    0
dtype: int64

In [ ]:
data['Student ID']=data['Student ID'].fillna('S207')
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    -45    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA     76     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA     78  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA     68      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
data['Name']=data['Name'].fillna('Rohan')
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    -45    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208   Rohan   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA     76     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA     78  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA     68      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
data['Age'].max()

25

In [ ]:
data['Age'].min()

-19

In [ ]:
data['Age'].mean()

np.float64(18.8)

In [ ]:
data['Gender']=data['Gender'].str.strip()
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    -45    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208   Rohan   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA     76     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA     78  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA     68      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
data['Age']

0     20
1     25
2     21
3     19
4     25
5     22
6     21
7     20
8    -19
9     22
10    20
11    21
12    22
13    20
14    23
Name: Age, dtype: int64

In [ ]:
data.shape

(15, 8)

In [ ]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
dtype: bool

In [ ]:
data.drop_duplicates()
data

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   25  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   25    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    -45    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208   Rohan   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
10       S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
11       S212   Divya   21  Female    MCA     76     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA     78  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA     68      Nepal     12-07-2023
14       S215  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
data.drop('Admission Date',axis=1)

   Student ID    Name  Age  Gender Course  Marks       City
0        S201   Rahul   20    Male    BCA     85  Bengaluru
1        S202   Priya   25  Female    BBA     78    Chennai
2        S203   Arjun   21    Male    BCA     92  Hyderabad
3        S204   Sneha   19  Female    MCA     88     Mysuru
4        S205   Kiran   25    Male    BBA     65  Bengaluru
5        S206  Anjali   22  Female    BCA    -45    Chennai
6        S207    Ravi   21    Male    MCA     95      Delhi
7        S208   Rohan   20  Female    BCA     72  Hyderabad
8        S209   Manju  -19  Female    BBA     80  Bengaluru
9        S210  Suresh   22    Male    MCA     89    Chennai
10       S201   Rahul   20    Male    BCA     85  Bengaluru
11       S212   Divya   21  Female    MCA     76     Mysuru
12       S213  Naveen   22    Male    BCA     78  Hyderabad
13       S214   Pooja   20  Female    BBA     68      Nepal
14       S215  Mahesh   23    Male    MCA    105  Bengaluru

In [ ]:
data.shape

(15, 8)

In [ ]:
import pandas as pd
import numpy as np
data=pd.read_excel("Student Data.xlsx")
data

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student ID      14 non-null     object
 1   Name            14 non-null     object
 2   Age             14 non-null     float64
 3   Gender          15 non-null     object
 4   Course          14 non-null     object
 5   Marks           14 non-null     float64
 6   City            14 non-null     object
 7   Admission Date  15 non-null     object
dtypes: float64(2), object(6)
memory usage: 1.1+ KB

In [ ]:
data.dtypes

Student ID         object
Name               object
Age               float64
Gender             object
Course             object
Marks             float64
City               object
Admission Date     object
dtype: object

In [ ]:
data.head(9)

  Student ID    Name    Age  Gender Course  Marks       City Admission Date
0       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1       S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2       S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3       S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4       S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5       S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6        NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7       S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8       S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023

In [ ]:
data.tail()

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
10       S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
data.isnull().sum()

Student ID        1
Name              1
Age               1
Gender            0
Course            1
Marks             1
City              1
Admission Date    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
print(data['de'].unique())

['M' 'Female' 'Male' 'F']

In [ ]:
data['Age'].std()

36.90200864124122

In [ ]:
data.dropna(axis=1)

    Gender Admission Date
0        M     12-06-2023
1   Female     15-07-2023
2     Male     10-08-2023
3        F     20-06-2023
4     Male     10-07-2023
5   Female     15-07-2023
6        M     01-08-2023
7   Female     22-08-2023
8        F     10-07-2023
9     Male     05-08-2023
10       M     12-06-2023
11  Female     18-07-2023
12    Male     25-08-2023
13  Female     12-07-2023
14    Male     30-06-2023

In [ ]:
data['Age'].var()

1361.7582417582416